/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedDeckRouteImport } from './routes/_authenticated/deck'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDeckRoute = AuthenticatedDeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck': typeof AuthenticatedDeckRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck': typeof AuthenticatedDeckRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/deck': typeof AuthenticatedDeckRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deck' | '/library' | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deck' | '/library' | '/studio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/deck'
    | '/_authenticated/library'
    | '/_authenticated/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/deck': {
      id: '/_authenticated/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof AuthenticatedDeckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDeckRoute: typeof AuthenticatedDeckRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDeckRoute: AuthenticatedDeckRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
